### ISSUE TITLE
Issue with "." when time values are written in the lua program for each sub controller

### ISSUE THREAD

**Issue by Pierremkb29** [danielathome19/MIDIToComputerCraft#1]
In the lua files created with your program, the time instructions are written using a "," instead of a "."
I give you an example with chpn-p4b (your original program given with the demo) and Pirates (My program created using your code)
[Pirates.txt](https://github.com/danielathome19/MIDIToComputerCraft/files/9543521/Pirates.txt)
[chpn-p4b.txt](https://github.com/danielathome19/MIDIToComputerCraft/files/9543523/chpn-p4b.txt)
Thank you for your project anyway
Have a good day
Pierre_mkb

**Comment by danielathome19** [comment]
@Pierremkb29 this might be a language issue depending on your localization; I calculate the sleep duration using the following line:
```if (key > timepassed) sb.Append($"sleep({key - timepassed})\n");```
So the script is just calculating the difference (i.e., `sleep(difference)` ) as a float. Your compiler might be set to a language setting that delimits decimals using commas.
