### ISSUE TITLE
[heads up!] CC:T Lua Does support "multithredding"

### ISSUE THREAD

**Issue by Merith-TK** [danielathome19/MIDIToComputerCraft#2]
So I saw in the video you mentioned Lua doesnt support multithreadding, 
But with CC you can do something that is basically the same thing!

https://tweaked.cc/module/parallel.html

its a little weird, but it actually works really well!

**Comment by danielathome19** [comment]
I did try using these at one point but found that it was either more accurate without them or about the same; it's close to multithreading, but instead, it constantly switches tasks until one is complete. True concurrency like C# or Golang would be the best solution in general, but it's good enough for what I wanted at least!
